### ISSUE TITLE
Update Metrics

### ISSUE THREAD

**Issue by lucadiliello** [lucadiliello/transformers-lightning#23]
Update metrics in `utils` to be compatible with the new released metrics package by `pytorch_lightning`

**Comment by matteogabburo** [comment]
In the main README.md the part related to the old parameter "--dataset_style iter" should be replaced with "--iterable_datasets"

**Comment by lucadiliello** [comment]
Main README is out-to-date and should be rewritten asap. This problem is addressed in the issue #13
