### ISSUE TITLE
MRPC test in GLUE benchmark

### ISSUE THREAD

**Issue by lucadiliello** [lucadiliello/transformers-lightning#31]
By evaluating 2 different models on the GLUE benchmarks, I noticed that the MRPC task gave the same results with both models and that standard deviation of different runs was 0.

Here the result of the two runs:
```
mrpc
model   eval_accuracy   eval_f1
bert    0.684 (+-0.0)   0.812 (+-0.0)
```
and 
```
mrpc
model   eval_accuracy   eval_f1
bert    0.684 (+-0.0)   0.812 (+-0.0)
```

Is it normal?

**Comment by matteogabburo** [comment]
I checked the output of the script and to me seems everything ok (with a clean GLUE run made yesterday).

Can you post the output of ```summarize_GLUE_results.py -i RESULTS/GLUE_RESULTS --percentual --std_deviation```?
